[Settings]
# Values define the raw buffer size and do not include the header size
MaxInputBuffer=16384
MaxOutputBuffer=16384

[Command]
# Number of worker threads executing normal commands.
CommandThreads=2

[Stream]
MaxQueuedStreamChunks=4
MaxQueuedStreamEvents=16
StreamThreads=4