# Defines which features will be enabled.
#
# A feature is enabled by providing a config file:
#   Feature=ConfigFile.conf
#
# To use the default configuration, set the value to "Enable":
#   Feature=Enable

Logger=Logger.conf
Server=Server.conf
Protocol=Protocol.conf
WakeOnLan=WakeOnLan.conf
Cloud=Cloud.conf