# Defines which features will be enabled.
#
# A feature is enabled by providing a config file:
#   Feature=ConfigFile.conf
#
# To use the default configuration, set the value to "Enable":
#   Feature=Enable

Server=Enable
WakeOnLan=WakeOnLan.conf